<?php 
return array (
  'site_name' => '狗扑微信公众平台',
  'site_title' => '狗扑微信公众平台',
  'site_url' => 'http://test.gope.cn',
  'site_my' => '狗扑微信平台TM',
  'server_key' => 'D27897844bc35e217de79b30b3567356',
  'server_topdomain' => '',
  'connectout' => '您的请求数量已经用完，请联系客服！',
  'ischeckuser' => 'false',
  'reg_needmp' => 'true',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'ipc' => '',
  'site_qq' => '75943938',
  'baidu_map_api' => 'D27897844bc35e217de79b30b3567356',
  'site_email' => '75943938@qq.com',
  'keyword' => '狗扑微信公众平台，国内最大的微信公众智能服务平台，微盟八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'content' => '狗扑微信公众平台，国内最大的微信公众智能服务平台，微盟八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
  'countsz' => '',
  'copyright' => '狗扑微信公众平台，国内最大的微信公众智能服务平台，微盟八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。',
);